### ISSUE TITLE
Table - Auto-hide pagination if there is only one page

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#104]

**Comment by jwildfire** [comment]
Test Notes: all pagination should be hidden when there is only a single page (that is when the # of items per page is greater than or equal to the total number of rows). This should work seamlessly with filters. Filtering down to one page should hide pagination. Filtering from one page to multiple pages should show the pagination.

**Comment by mhickle** [comment]
Pass
![3](https://user-images.githubusercontent.com/31038805/30864769-a412e8e6-a2a2-11e7-9fc3-c46f69129d4b.PNG)
