### ISSUE TITLE
No ellipse should display

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/Webcharts#106]
No ellipse should display if there are fewer than or the same number of pages as the number of page links displayed.

**Comment by jwildfire** [comment]
Think this is only happening when the number of pages matches config.nPageLinksDisplayed

**Comment by jwildfire** [comment]
Test Notes: '...' should be hidden whenever the link for the last page is visible (this includes when `nPageLinksDisplayed` is less than or equal to the total number of pages.)

**Comment by mhickle** [comment]
Pass
![2](https://user-images.githubusercontent.com/31038805/30863849-13fdcbba-a2a0-11e7-870e-1228ab83a209.PNG)
