### ISSUE TITLE
Table: Filtering down to 0 elements should print an error message

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#109]
currently just throws a error in the console.

**Comment by jwildfire** [comment]
Test Notes: Use the filters and search bars to make empty tables and make sure a note is displayed.

**Comment by mhickle** [comment]
This is currently what happens when no input is in the table. Is that the expected output ? 
![9](https://user-images.githubusercontent.com/31038805/30865450-a937a80a-a2a4-11e7-8246-45ba0a47278c.PNG)

**Comment by mhickle** [comment]
Pass 
![14](https://user-images.githubusercontent.com/31038805/30866291-cba6cdb0-a2a6-11e7-8f28-f3e2b58b2002.PNG)
