### ISSUE TITLE
Add a max-width argument for marks with type=bar

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#112]
With sparse data, we regularly get charts where a single bar takes up an entire plot (See below). Can be overcome with range_band, but then you run the risk of the bars not scaling well when there are lots of observations later on. Should be doable by putting a quick logic check on range_band on resize. 

<img width="480" alt="screen shot 2017-09-21 at 9 23 05 am" src="https://user-images.githubusercontent.com/3680095/30707702-34ccce24-9eb1-11e7-9228-b087dce26993.png">

**Comment by jwildfire** [comment]
On second thought, I think range-band is sufficient here. Closing.

**Comment by samussiah** [comment]
That's a lot of extraneous _data ink_.
