### ISSUE TITLE
# of items per page setting is ignored after changing # of page links setting

### ISSUE THREAD

**Issue by emmorris** [RhoInc/Webcharts#113]
In the most recent example with pagination (https://rhoinc.github.io/viz-library/examples/0020-webcharts-table/example.html) there appears to be a bug with the # of items per page setting.  

Steps to reproduce:
1. Leave "# of items per page" set to 10 and change "# of page links" to 4.
2. Hit "Enter" for the changed setting to take affect.
3. Click the ">" icon to go to the next page.
4. You should see that there are no longer only 10 items displayed on the page.  

The "# of items per page" setting appears to work as you flip between pages until you change the page links setting.

**Comment by dschwentker** [comment]
I see similar behavior when changing the # of page links page setting as well.

**Comment by jwildfire** [comment]
Bug was in code for the example (not for webcharts). Example is fixed now, so closing this issue as invalid (since no code was changed in webcharts)
