### ISSUE TITLE
Table: Add a note next to the search giving the number of matches for the current term. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#118]
A bit messy with the current data flow, but should be easy after 119.

**Comment by jwildfire** [comment]
Test Notes: Confirm that note next to search is accurate and responsive. Should give total records when search and filter are empty and "n/N" when search or filter is active.

**Comment by mhickle** [comment]
![26](https://user-images.githubusercontent.com/31038805/31092249-c5e12f5e-a77b-11e7-9dfe-754d9fedb660.PNG)
