### ISSUE TITLE
Table: Streamline Search and Sort UI

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#120]
Combine Search and sort functionality into a single div.

**Comment by samussiah** [comment]
Sort and search are contained within `.table-top` now and floated left and right respectively.  Export and pagination are contained within '.table-bottom' now and floated left and right respectively.  Still need to figure out where to display number of records filtered/searched/paginated.

**Comment by jwildfire** [comment]
I'm thinking we can move the "Search:" label to the default text for the input, and use that space to show the number of records.

**Comment by jwildfire** [comment]
Test Notes: 
Confirm that search and sort appear in the header and that pagination and export appear in the footer and all look good in various browsers/combinations. Note that #128 is handled in a separate issue.

**Comment by mhickle** [comment]
Pass

IE:
![23](https://user-images.githubusercontent.com/31038805/31092101-5544ba40-a77b-11e7-9b93-61f6fd257632.PNG)
Google Chrome:
![24](https://user-images.githubusercontent.com/31038805/31092130-6b4752f8-a77b-11e7-82f1-708c7c9e4872.PNG)
Firefox:
![25](https://user-images.githubusercontent.com/31038805/31092159-7f8cceaa-a77b-11e7-9e50-184950b9609d.PNG)
