### ISSUE TITLE
Sorting on several columns overlaps search

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#128]
<img width="722" alt="screen shot 2017-09-28 at 5 17 25 pm" src="https://user-images.githubusercontent.com/3680095/30996338-08195ac2-a475-11e7-97f8-ab423eef5268.png">

**Comment by jwildfire** [comment]
Test Notes: Confirm that Search and Sort sections no longer overlap (as shown in the screenshot above).

**Comment by mhickle** [comment]
Pass

![30](https://user-images.githubusercontent.com/31038805/31280121-4b95b98a-aa79-11e7-95aa-86352f9a238e.PNG)
