### ISSUE TITLE
Add option to draw legend above the chart

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#13]
Add option to insert the legend before svg (instead of after). We could also consider legends to the right and left, but thinking those introduce more complicated layout issues ...

**Comment by nbryant** [comment]
would probably add a new config option like this:

```javscript
legend: {
  location: 'top',
  label: 'My legend',
  ...
}
```

**Comment by jwildfire** [comment]
Sounds reasonable to me. I'd say we have the default = `location: "bottom"`

**Comment by nbryant** [comment]
done in v1.5.0
