### ISSUE TITLE
Table: Should use table.config.cols in sort buttons

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#135]
When available, use column labels in sort order section.

<img width="676" alt="screen shot 2017-10-03 at 7 29 32 am" src="https://user-images.githubusercontent.com/3680095/31130617-bb1e8db4-a80c-11e7-9f8c-d8cf51fdd24b.png">

**Comment by jwildfire** [comment]
Test Notes: 
- Use the shift plot renderer to confirm that labels are shown in the sort order instead of column names (when available). Sort item should be labeled "Baseline value" instead of "shiftx" in the chart above. 
- Use example 20 to confirm that sort buttons work as expected when no labels are provided (no change from previous version should be seen).

**Comment by mhickle** [comment]
Pass

![34](https://user-images.githubusercontent.com/31038805/31341458-84d5b352-acd7-11e7-8054-7df3a53ea002.PNG)
