### ISSUE TITLE
Table header doesn't update on table.draw()

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#139]
In the current v1.9.0 build, the table header is only modified in `table.layout()`. This means that modifying `table.config.cols` or `table.config.headers`  after `table.init()` is called causes problems like in [this issue](https://github.com/RhoInc/ae-timelines/issues/35) in the ae-timeline repo.

**Comment by jwildfire** [comment]
Don't see any major problem with setting up `thead` in `table.layout()` and then using the standard enter/update/exit paradigm for the `th`cells in `table.draw()`

**Comment by samussiah** [comment]
Test notes:

* Verify column list and order is randomized upon clicking the _Randomize columns_ button.
* Verify headers match data in columns upon clicking the _Randomize columns_ button.
* Verify header text is randomized upon clicking the _Randomize headers_ button.

**Comment by mhickle** [comment]
Pass
