### ISSUE TITLE
Deleting a sort item should trigger a sort

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#140]

**Comment by jwildfire** [comment]
Test Notes: Confirm that:
- deleting all sort items returns the chart to it's original order (previously no change was made)
- when 2 sort items are specified, deleting the first item in the list activates a new sort using the remaining item.

**Comment by mhickle** [comment]
Pass

![28](https://user-images.githubusercontent.com/31038805/31279850-85c6ffde-aa78-11e7-9ed1-e1b0943af75c.PNG)
![29](https://user-images.githubusercontent.com/31038805/31279849-85be23b4-aa78-11e7-94ae-fcdd6a231d72.PNG)
