### ISSUE TITLE
Typo in name of export file

### ISSUE THREAD

**Issue by emmorris** [RhoInc/Webcharts#145]
When you export the data from the webcharts table example the file is named "webhartsTableExport..." instead of "webchartsTableExport...".

**Comment by emmorris** [comment]
Ready to test in https://rhoinc.github.io/viz-library/examples/0020-webcharts-table/

**Comment by mhickle** [comment]
Fail- Im still seeing this issue in all browsers 

Chrome:
![31](https://user-images.githubusercontent.com/31038805/31280201-979ace4c-aa79-11e7-830d-88312ce3b941.PNG)

Firefox:
![32](https://user-images.githubusercontent.com/31038805/31280299-e5c9625e-aa79-11e7-9844-3df1b75e8ffc.PNG)

IE:
![33](https://user-images.githubusercontent.com/31038805/31280304-ea444c0e-aa79-11e7-8988-1e35461d3c55.PNG)

**Comment by mhickle** [comment]
Pass 

![37](https://user-images.githubusercontent.com/31038805/31349065-a7f26138-acef-11e7-9975-a1e3dac41057.PNG)
