### ISSUE TITLE
Minor table style tweaks

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#147]
Use (some of) the following from web-codebook:

```
        .web-codebook  .listing-container table {
            width: 100%;
            border-collapse: collapse;
        }

        .web-codebook  .listing-container thead tr {
            border-bottom: 2px solid black;
        }

        .web-codebook  .listing-container tbody tr {
            border-bottom: 1px dotted #ccc;
        }

        .web-codebook .listing-container td, .web-codebook .listing-container th {
            text-align: left;
            padding: 2px 5px;
        }
```

**Comment by jwildfire** [comment]
Went with less padding and borders above and below the `tbody`

**Comment by jwildfire** [comment]
Test Notes: Confirm that:
- a 2px thick black line is drawn beneath the thead (was 1px and gray)
- a 1px black line is drawn below the last row of the table (no line was drawn previously)
- Padding for each cell is 2px above and below the text and 5px on each side

**Comment by mhickle** [comment]
Pass
![27](https://user-images.githubusercontent.com/31038805/31279773-3faea358-aa78-11e7-9f1c-40fd91eaf1e1.PNG)
