### ISSUE TITLE
Renderers table formatting issue

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/Webcharts#152]
When testing the aetimelines renderer with Webcharts 1.9, we noticed that the table header with the instructions and search bar was getting smushed down to the sides of the table, rather than appearing above the table. For aetimelines, this is an issue in all three browsers (Chrome, Firefox, and IE 11), but for the safety-histogram and safety-shift-plot renderers noted below, it appears to only be an issue in IE 11.

![image](https://user-images.githubusercontent.com/17090469/31404220-6cde6c42-adc9-11e7-8030-edff6f8bb806.png)

**Comment by dschwentker** [comment]
I've subsequently noticed similar behavior in the safety-histogram renderer:
![image](https://user-images.githubusercontent.com/17090469/31454910-0708d198-ae85-11e7-9f43-bfb1d1e31011.png)

And the safety-shift-plot renderer:
![image](https://user-images.githubusercontent.com/17090469/31454944-1e369b98-ae85-11e7-824c-eaf0aa950782.png)

**Comment by jwildfire** [comment]
Test Notes: Confirm that this is fixed in `f11f634a2b9cb999af78a776e86d2dbcc1e78ad3`

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
