### ISSUE TITLE
applyCSS: false displays table interactivity elements even when they're disabled.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#160]

**Comment by jwildfire** [comment]
![image](https://user-images.githubusercontent.com/3680095/69076194-baa02280-0a11-11ea-8455-a91c88711626.png)

Looks like this is still an issue, but I don't think it's worth it to make updates here. Intent is really to give the user full control (and responsibility) of the css, so they can handle the pagination etc. or disable. 

[Updated the wiki](https://github.com/RhoInc/Webcharts/wiki/Table-Configuration#applycss) with an additional warning and closing this.
