### ISSUE TITLE
Legend is covered up slightly

### ISSUE THREAD

**Issue by emmorris** [RhoInc/Webcharts#164]
![image](https://user-images.githubusercontent.com/23057086/32024669-62c6426e-b9ab-11e7-9d35-fa8d90dc28b3.png)

As you can see in the screenshot from the Clinical Timelines chart, the legend is slightly covered up.  It looks like the controls box might be just a pixel too far down the page so the top of the circles are cut off.

**Comment by jwildfire** [comment]
Good eye, @emmorris. I'd never noticed, but now I can't unsee it!

**Comment by samussiah** [comment]
Fixed in v1.11.0.
