### ISSUE TITLE
Pagination arrow ordering for data listing is incorrect in RhoMAP

### ISSUE THREAD

**Issue by emmorris** [RhoInc/Webcharts#169]
RhoMAP was recently updated to the most recent version of webcharts and there appears to be a bug in the pagination.  As you can see below, the double arrow option should be last, but for some reason in RhoMAP it is listed before the single arrow after the page numbers.  The arrows before the page numbers still have the correct order.  This issue is present in all of the renderers that use webcharts for the data listing: AE Timelines, Safety Histogram, Safety Shift Plot, Codebook, Query Overview, Paneled Outlier Explorer, and Clinical Timelines.

![image](https://user-images.githubusercontent.com/23057086/35003278-588e53c2-faba-11e7-8c76-33d2528b13bb.png)

If you inspect the element in RhoMAP and the CAT it appears to be coded the same way: 
![image](https://user-images.githubusercontent.com/23057086/35003390-ba9abda8-faba-11e7-8ebb-d323c653b9b4.png)

**Comment by samussiah** [comment]
Update .right to .wc-right or something.

**Comment by emmorris** [comment]
There is still an unmerged pull request for CSS conflict changes. 
 We should make sure this gets added to that since I don't believe it was. 
 https://github.com/RhoInc/Webcharts/pull/158
