### ISSUE TITLE
Bind the Table object to the DOM

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#182]
Similar to #180, but the table workflow in `table.transformData()` might need to be reworked a bit.

# Test notes
* Load a renderer with a Webcharts table, such as query-overview.
* In the developer console (hit F12), run `d3.select('.wc-table').datum()` and verify that a Webcharts table object is returned, i.e. an object with properties `data`, `wrap`, `table`, `config`, etc.

**Comment by dschwentker** [comment]
Tested and confirmed that a Webcharts table object is now returned, instead of an array object.
