### ISSUE TITLE
Prevent data inheritance in children of chart.wrap and controls.wrap.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#188]
#180 creates unwanted data inheritance of the chart/controls object to children of their `wrap`s, e.g. `chart.svg`, as described in [this d3 issue](https://github.com/d3/d3/issues/1443).  This data propagation has the unwanted side effect of unexpected brushing behavior in the [safety-shift-plot](https://github.com/RhoInc/safety-shift-plot) and [paneled-outlier-explorer](https://github.com/RhoInc/paneled-outlier-explorer) and issues with the controls in the [clinical-timelines](https://github.com/RhoInc/clinical-timelines).

# Test notes
* Verify that the issues with these three renderers in CAT are rectified.

**Comment by dschwentker** [comment]
Tested and passed using webcharts v1.10.0-dev in CAT.
