### ISSUE TITLE
Global Legend within individual Multiplied Chart div

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/Webcharts#190]
When making paneled bar charts with .multiply(), the legend is a child of the div for the last chart causing the chart title to be offset from the chart (since it's being centered on the width of the legend, not the chart) and the last chart to be isolated. 
![image](https://user-images.githubusercontent.com/26064686/37615251-304f79f0-2b83-11e8-8387-d316518fdc32.png)

# Test notes
* Verify that the legend appears either after and outside the small multiples or before the small multiples when `legend.top` is set to `'top'`.
* [Old functionality](http://interactive.it.rhoworld.com/dev/projects/295/panel_hist/master/)
* [New functionality](http://interactive.it.rhoworld.com/dev/projects/295/panel_hist/multiples-legend%20branch/index.html)

**Comment by danedexF5** [comment]
Looks good. The old funcionality has the legend appearing within the div chart. The new functionality has the legend moved outside of that div and into it's own li.
