### ISSUE TITLE
create a 'preprocess' event for table objects

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#192]
The callback should be run at the beginning of the `table.draw()` function. 

# Test notes
* No need to feature test.

**Comment by jwildfire** [comment]
@emorris @samussiah @pburnsdata slotting this in to v1.11.0 since it would make the data flow in the new RAVE heatmap renderer quite a bit easier. I think it's just a couple of lines of code to define the new callback and then run it at the beginning of `table.draw()`.

**Comment by dschwentker** [comment]
Ne testing needed
