### ISSUE TITLE
Percent domain is broken.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#223]
per @nandriychuk

**Comment by samussiah** [comment]
[in setDomain.js](https://github.com/RhoInc/Webcharts/blob/master/src/chart/draw/consolidateData/setDomain.js#L61), should be `'summarize' + axis` rather than `'summarize' + otherAxis`

**Comment by dschwentker** [comment]
Tested and passed, using the Bar Charts: Data Summaries + Grouping group in Webcharts Visual Tests, and Test #7 (Vertical Bar chart:summarizeY = percent)
