### ISSUE TITLE
Multiples Changes Lost

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/Webcharts#225]
It appears like some of the code from #201 was lost (e.g. https://github.com/RhoInc/Webcharts/pull/201/commits/2e283f50deefa3a2afc554740b731433962d2edf  vs.  line 207 of [master](https://github.com/RhoInc/Webcharts/blob/master/build/webcharts.js).)

**Comment by dschwentker** [comment]
Tested and checked that the legend is rendered as expected in preston's example page
(Used: http://interactive.it.rhoworld.com/dev/projects/295/panel_hist/ and compared the two versions -> for v1.11.1 the legend is no longer in the div of the last chart (and the title for that last chart consequently isn't dragged way over to the right.)
