### ISSUE TITLE
'clip-path' of all marks should default to `url(#${chart.id})`.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#235]
# Test notes
* No testing needed for this one.  Technical changes.

**Comment by jwildfire** [comment]
@samussiah @pburnsdata Any idea why only `drawBars` has a clip-path property?  Is the goal of this issue to add a clip-path to other marks, to fix the clip-path for bars, or both?

**Comment by samussiah** [comment]
Not sure, but the goal here is to contain the marks to their corresponding chart's canvas.  We often set `clip-path` manually but when would it ever be set to anything other than the chart canvas.

**Comment by pburnsdata** [comment]
I don't know either but this would be a fix for bars - not the other marks. I can't think of any other situations...

**Comment by samussiah** [comment]
The issue arises when plotting marks that fall outside the x- or y-domain, for instance when applying a custom domain.  Setting their `clip-path` prevents them from displaying.

**Comment by pburnsdata** [comment]
Ahhh gotcha, that makes sense. Wouldn't hurt to add this to drawLines and drawPoints then right?

**Comment by samussiah** [comment]
That's what I was thinking.  I'd include text for consistency; we can always extend the margins or reposition the text to prevent clipping.
