### ISSUE TITLE
Add a workaround for Webcharts All subsetter logic.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#236]
If the filter variable has a value of _All_ Webcharts counts _All_ twice.

# Test notes
* Verify that if _All_ appears in a variable underlying a filter, it also appears as an option in the filter dropdown separate from the default _All_ option:
  * Choose a renderer with a default _All_ filter: ae-timelines, crf-heat-map, participant-visit-listing, or clinical-timelines.
  * Download the data file.
  * Add a value of _All_ to one of the _All_ filter columns.
  * Upload the modified data file.
  * Render the chart and verify the filter contains two _All_ options, one that selects all data and one that selects only the modified record.

**Comment by jwildfire** [comment]
@samussiah Is there an easy fix for this? If so, shall we address along with #238 in v1.11.3?

**Comment by samussiah** [comment]
Webcharts has logic [here](https://github.com/RhoInc/Webcharts/blob/master/src/chart/draw/consolidateData.js#L13) that doesn't allow a value of _All_ in the data to filter correctly.  It's an edge case and one that can be avoided by replacing _All_ with a different value (_Overall_, _All Records_, etc.).  More difficult to fix than I figured.

**Comment by samussiah** [comment]
[issue](https://github.com/RhoInc/ae-timelines/issues/70) logged to address _All_ subsetter logic in ae-timelines

**Comment by danedexF5** [comment]
It works mostly. There is an edge case where updating a field to All can error CRF, CT and PVL. Spencer is aware and there are issues opened for those 3 renderers.
