### ISSUE TITLE
Document "Require" option for controls. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#24]
Remove old "required" option

**Comment by emmorris** [comment]
We need to think about what we may have intended when we created this.  Is there still an option for required in the code?  

Update wiki accordingly.

**Comment by samussiah** [comment]
Adds a bright red bordered _Required_ `span` to the control group.

**Comment by samussiah** [comment]
The [controls configuration wiki](https://github.com/RhoInc/Webcharts/wiki/Controls) already describes the `required` setting.
