### ISSUE TITLE
Add documentation for table configuration options

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#25]

**Comment by jwildfire** [comment]
Probably makes sense to do this in conjunction with #43

**Comment by jwildfire** [comment]
Created page [here](https://github.com/RhoInc/Webcharts/wiki/Table-Configuration). Needs details.

**Comment by jwildfire** [comment]
Test notes: Page updated [here](https://github.com/RhoInc/Webcharts/wiki/Table-Configuration) , please QC for clarity, grammar and formatting.

**Comment by mhickle** [comment]
Pass
