### ISSUE TITLE
onResize callback running before marks finish renderering/transitioning.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#255]
consider running onResize callback on transition end event.

**Comment by jwildfire** [comment]
I think this makes sense, but also wonder if there's some chance it would introduce some unexpected behaviour in renderers. Was there a specific use case where we know this was firing too early? Or was it just a general issue you noticed?

**Comment by samussiah** [comment]
I don't remember where I ran into this 😞 but this might pop up with a huge number of marks that take a long time to render...

**Comment by samussiah** [comment]
Can't reproduce.
