### ISSUE TITLE
Add dataTables-esque functionality to createTable()

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#43]

**Comment by emmorris** [comment]
Reference the changes made here:https://github.com/RhoInc/web-codebook/tree/master/src/chart/dataListing

**Comment by emmorris** [comment]
We should still give the user the option to turn off all the formatting and fancy things.

Keep options for sorting, searching, etc.

**Comment by jwildfire** [comment]
New issues created covering the details. Closing as duplicate.
