### ISSUE TITLE
Add Unit Testing Suite

### ISSUE THREAD

**Issue by samussiah** [RhoInc/Webcharts#53]
Copying @nbryant

**Comment by samussiah** [comment]
Consider switching from jsdom (which doesn't handle webpage layout) to phantomJS or headless Chrome.

**Comment by jwildfire** [comment]
The original tests from @nbryant are [here](https://github.com/RhoInc/Webcharts/tree/v2-refactor/test)

**Comment by jwildfire** [comment]
Initial framework in place (along with travisCI integration) in `v1.7.2-dev` branch
