### ISSUE TITLE
Chart ConfigurationTests: Scatter plots

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#58]
Use the elements test data to create valid config objects that test all relevant iterations of:

x.type = [log,linear]
y.type = [log, linear]
mark.type = [circle, line, text]
per = [[element], [group]]  (use summarizeX = summarizeY = 'mean')

This should produce 2 x 2 x 3 x 2 = 24 charts.

**Comment by jroden** [comment]
got it

**Comment by jroden** [comment]
Do we want to shorten this one down?

**Comment by jwildfire** [comment]
I think we might be able to get away with keeping all 24 test cases, but the current objects aren't rendering for me. 

<img width="1329" alt="screen shot 2017-06-08 at 12 01 23 pm" src="https://user-images.githubusercontent.com/3680095/26945935-59faa336-4c42-11e7-8983-b9ca67db9eee.png">

**Comment by jwildfire** [comment]
Actually, I think this might be because of the re-org - I'll see if i can debug real fast.

**Comment by jwildfire** [comment]
Got it working (see commit above)  - leaving out lines for now. 

There are issues with using type="log" when there are 0 and/or missing values in the specified column. Will add an issue to deal with that in an upcoming release.
