### ISSUE TITLE
Chart Configuration Tests: Bar Charts

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#59]
Use `mark.type = bar` and then figure out a reasonable set of states for the following options:
- x.type and y.type  (perhaps in conjunction with x.bins and y.bins)
- marks.split
- marks.arrange
- possibly marks.summarizeX and marks.summarizeY

**Comment by jroden** [comment]
got it
Defined statespace cubes::
1.     Locked x axis = ordinal; y axis = [linear, log]; split = boolean (dual_state); arrange =[*all possible states]        
        summarizeY = [*all possible states]

2.    Locked y axis = ordinal;  *Same statespace as above but switch x & y

3&4. *Repeating the same cases as above, but with locked axes at ordinal and linear to test x & y bins

total cases currently: 287

**Comment by jwildfire** [comment]
Instead of one tests suite with 287 items, I'd like to get this down to a series of multiple "test suites" with no more than 20 tests (less than 10 is ideal). I'll look more closely and try to come up with a list today.

**Comment by jwildfire** [comment]
Bar Chart Test Suites: 
1. Horizontal Axis Types (5 types)
- constants
  - x.type = categorical
  - mark.type = bar
  - split = null
  -  y.column = continuous variable unless noted
- variables y.type
 - "linear"
 - "linear" + (column=null, bin =10)
 - "log"
 - "time"
 - "ordinal" (should fail)
 
2. Vertical Axis types (5 cases)

notes: same as above by switch x and y)

3. Grouped Bar charts (10 cases) 

notes: same as 1/2 above, but add the following constants: 
Additional constants: 
- arrange = "grouped"
- split = marks.per = color_by = a valid categorical variable

4. Stacked bar charts (10 cases) 

notes: same as 3., but with arrange = stacked 

5. Nested bar charts (10 cases) 

notes: same as 3/4 but with arrange  = nested

6. SummarizeY + Grouped (8 cases)

Constants: same as 1. with y.type set as linear. 
New Variable = summarizeX (use all 8 valid options)

7. SummarizeY + Stacked (8 cases)

 notes: similar to 6 with stacked
 
8. SummarizeY + Stacked (8 cases)

similar to 6/7 with nested

**Comment by jwildfire** [comment]
Skipping nested bars for now. Going to mark that as "Experimental"
