### ISSUE TITLE
Chart Configuration Tests: Chart Sizing

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#60]
Develop a set of test cases to make sure charts render at the specified size. Tests focus on these settings:

config.width
config.height
config.max_width
config.resizable
config.margin
config.aspect

**Comment by jroden** [comment]
ayup, 95 cases covering the above

**Comment by jwildfire** [comment]
Let's break this down in to several smaller sets of tests.

Suite 1: resizable = true. (8 tests)
- Test 2 options each for height/width, max_width and aspect. 

Suite 2: resizable = false (8 tests)
- Test height/width, max_width and resizable. 

Suite 3: margins (10 tests)
- Test each of 4 margins margin individually for 2 different height/width combinations. then set all margins to different values
