### ISSUE TITLE
Chart Configuration Tests : Axis Combinations

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#61]
Develop a set of tests to confirm that basic axis combinations work as expected in various situations. Focus on these settings for x/y type:

- linear/linear
- linear/log
- linear/ordinal
- linear/time
- log/log
- log/ordinal
- log/time
- ordinal/ordinal
- ordinal/time
- time/time

(10 cases)

**Comment by jroden** [comment]
it appears we're only generating 8 charts for this case, seems small enough as long as its good coverage

**Comment by jwildfire** [comment]
Updated this to broadly cover axes rendering as expected.
