### ISSUE TITLE
Chart Configuration Tests: Data Summary

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#62]
Create a set of configurations to confirm that marks.summarizeX and marks.summarizeY behave as expected. Might make sense to have several different marks in the same chart to confirm this.

**Comment by jroden** [comment]
Already covered in the bar chart suite with several combinations of marks.
Should I do some summarizeX and Y cases where the chart is line/scatter?

**Comment by jroden** [comment]
LMK what you think:
Suite 1:
      SummarizeX (about 8 i think options)
suite 2:
      SummarizeY (ditto)
suite 3:
     SummarizeX + SummarizeY (couple more in here, no more than 10?)

**Comment by jwildfire** [comment]
I think we might actually just have this covered in the other tests - [this commit](https://github.com/RhoInc/Webcharts/commit/219f73c52a58b5cf6ede50052ee1414005750ff6) in particular.
