### ISSUE TITLE
Color Scale includes unexpected undefined value

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#67]
From unit tests: 

<img width="919" alt="screen shot 2017-06-05 at 4 21 36 pm" src="https://cloud.githubusercontent.com/assets/3680095/26807401/15b83b4a-4a0b-11e7-9b2a-b2c427b60511.png">

**Comment by jwildfire** [comment]
@samussiah Any thoughts about what is causing this to fail?

**Comment by samussiah** [comment]
Yep, when no argument to `color_by` is provided a value of `undefined` is passed to the color scale.  And in the case above I was testing how the color scale behaved when an argument to `color_dom` is provided without `color_by`.

**Comment by jwildfire** [comment]
So, it's merging the arrays instead of just using color_dom? 

Let's go ahead and fix this in 1.8.

**Comment by jwildfire** [comment]
Looks like the test is failing because drawPoints() is hitting config.colorScale() with a null value [here](https://github.com/RhoInc/Webcharts/blob/unit-tests/src/chart/drawPoints.js#L33-L34): `.attr('fill', d => this.colorScale(d.values.raw[0][config.color_by]))` which leads to the creation of a new `undefined` element in the domain. 

I'm not sure there's an way around this implementation, so I'm leaning towards replacing the test where we look at color_dom without a cooresponding color_by for a test that has both values.

**Comment by jwildfire** [comment]
updated tests [here](https://github.com/RhoInc/Webcharts/commit/967111e616ef88217db7bf12f48c5a0e57b9ad93). closing.
