### ISSUE TITLE
Add destroy method for table

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#68]

**Comment by jwildfire** [comment]
Test notes: Can be tested using [this page](https://rhoinc.github.io/viz-library/examples/0021-webcharts-destroy-table/). Confirm that the table is deleted after 5 seconds.

**Comment by mhickle** [comment]
Pass
![8](https://user-images.githubusercontent.com/31038805/30865145-cdde7482-a2a3-11e7-9a9f-ee5cb237ed03.PNG)
