### ISSUE TITLE
Tables - add option for sortable column headers

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#94]
Click a row header to sort the table. Click again to switch order. Click the label to remove the sort parameter.

**Comment by jwildfire** [comment]
Test Notes:
- Confirm that data sorts as expected when clicking a column header
- Confirm that a second click reverses the sort order
- Can sort on multiple headers (click a second column header to initialize)
- Clicking the label removes the search term
- Confirm that sort works with pagination
  - Can sort from a later page (should stay on the same page, but records should change)
  - Pagination controls show you the appropriate sorting (later pages are later in the sort order)
- Confirm that sort works with search.
  - can sort search results. 
  - initializing a search maintains the current sort order.

**Comment by mhickle** [comment]
1)![15](https://user-images.githubusercontent.com/31038805/30866317-e3e3e08e-a2a6-11e7-91aa-d8f988d970b7.PNG)
2)![16](https://user-images.githubusercontent.com/31038805/30866339-f209b3fa-a2a6-11e7-8e67-cc2bb55e653a.PNG)
3) ![17](https://user-images.githubusercontent.com/31038805/30866366-041dccde-a2a7-11e7-96ca-648f2eb71803.PNG)
4)![18](https://user-images.githubusercontent.com/31038805/30866451-4781beea-a2a7-11e7-90a7-e7ad793cedd5.PNG)
5) ![19](https://user-images.githubusercontent.com/31038805/30866489-63c94d7a-a2a7-11e7-97db-117944fd8baa.PNG)
6) ![20](https://user-images.githubusercontent.com/31038805/30866671-eab5bc88-a2a7-11e7-8869-37f02120ed90.PNG)
