### ISSUE TITLE
Tables - add option for search functionality

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#95]

**Comment by jwildfire** [comment]
Just a note that there is already a `table.config.searchable` option in the code, but it is ignored unless `config.data_tables` is `true`

**Comment by jwildfire** [comment]
Test Notes: 
- Table should filter when typing in to the search box
- A note should be shown in the table for a search with no results
- search results should only contain data for the selected filters
- change a filter should reset the search results
- Pagination should update with the search
  - any search should take the user to page 1 of the results (regardless of the page the user was on when the search was initialized)
  - if there is more than 1 page of results, pagination controls should be shown
  - if there is only 1 page, pagination controls should be hidden
  - if there are no results pagination controls should be hidden
- should be able to search for numbers or characters.

**Comment by mhickle** [comment]
1) ![10](https://user-images.githubusercontent.com/31038805/30865997-16279aaa-a2a6-11e7-9cb7-01fe29d7cb6b.PNG)
2) ![14](https://user-images.githubusercontent.com/31038805/30866251-b13134ca-a2a6-11e7-8866-8f8b4f014cd0.PNG)
3) ![11](https://user-images.githubusercontent.com/31038805/30866059-38159158-a2a6-11e7-98e6-313c9781d406.PNG)
4) ![12](https://user-images.githubusercontent.com/31038805/30866080-4b0354b2-a2a6-11e7-9d1e-ff818f517b83.PNG)
5) ![13](https://user-images.githubusercontent.com/31038805/30866130-68f4011a-a2a6-11e7-9d32-fc5ca6b42920.PNG)
![14](https://user-images.githubusercontent.com/31038805/30866266-b9920cde-a2a6-11e7-86a1-dc797da8d949.PNG)
