### ISSUE TITLE
Tables - Add option for css styling

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#96]
Include some basic styling by default, but give user the option to deactivate

**Comment by jwildfire** [comment]
Point here is to allow the user to apply their own styles (without having to override ours) if desired ...   low-ish priority

**Comment by jwildfire** [comment]
Test Notes: Use the [example](https://rhoinc.github.io/viz-library/examples/0020-webcharts-table/example.html) to toggle the applyCSS setting, and see if the styling goes away ...

**Comment by mhickle** [comment]
Pass
![6](https://user-images.githubusercontent.com/31038805/30864995-5b02eb3c-a2a3-11e7-9460-bd79a23f8f05.PNG)
![7](https://user-images.githubusercontent.com/31038805/30864997-5ce33042-a2a3-11e7-80fd-bf334e9cd08e.PNG)
