### ISSUE TITLE
Tables - add option for export functionality

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#97]
I'm thinking we can start by supporting `settings.export: ["csv", "xlsx"]` (default: null)

**Comment by jwildfire** [comment]
Test notes: 
- Confirm that the exportable toggle shows/hides the download buttons in the footer
- Confirm that clicking the csv and xlsx buttons downloads files of the appropriate type in the following cases:
  - with/without filters
  - with/without search
  - with/without filters & search
  - with/without pagination (pagination should be ignored - all records should be downloaded)

**Comment by mhickle** [comment]
Pass
![20](https://user-images.githubusercontent.com/31038805/31092014-01f1fb46-a77b-11e7-8ec9-862e6605434b.PNG)
![21](https://user-images.githubusercontent.com/31038805/31092015-01f35ce8-a77b-11e7-9d2b-edb0f4e97768.PNG)
