### ISSUE TITLE
Tables - add option for pagination

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/Webcharts#98]

**Comment by samussiah** [comment]
Test notes:

- Pagination elements appear below table when the `pagination` option is set to `true`.
- Number of rows displayed at any given time is limited to the `nRowsPerPage` option, or 10 if unspecified.
- Number of page links displayed at any given time is limited to the `nPageLinksDisplayed' option, or 5 if unspecified.
- The double left arrow link displays the first page.
- The single left arrow link displays the previous page.
- An ellipse is displayed before the first numbered page link and after the single left arrow link if there are lower-numbered page links than the lowest currently displayed.
- An ellipse is displayed after the last numbered page link and before the single right arrow link if there are higher-numbered page links than the highest currently displayed.
- The single right arrow link displays the next page.
- The double right arrow link displays the last page.
- Pagination is reactive to filtered data.

**Comment by samussiah** [comment]
New options:

- `pagination`: boolean; paginate table?; no default so false-y
- `nRowsPerPage`: integer; number of rows displayed per page; defaults to 10
- `nPageLinksDisplayed`: integer; number of page links displayed; defaults to 5

**Comment by jwildfire** [comment]
Created #104 to automatically hide pagination when only one page is shown.

**Comment by jwildfire** [comment]
Added a few pagination test cases added under `test/samples/chart-config/tables_pagination.json` which can be accessed [here](https://rhoinc.github.io/CAT/webchartsTests/) by using version = "5472ef6156a30a79c6c9559482eb18871f41244b" and selecting "Tables: Pagination" from the dropdown.

**Comment by mhickle** [comment]
[X] Pagination elements appear below table when the  pagination  option is set to  true .
 [X] Number of rows displayed at any given time is limited to the  nRowsPerPage  option, or 10 if unspecified.
 [X] Number of page links displayed at any given time is limited to the  nPageLinksDisplayed  option, or 5 if unspecified.
 [X] The double left arrow link displays the first page.
 [X] The single left arrow link displays the previous page.
 [X] An ellipse is displayed after the single left arrow link and before the first numbered page link if there are lower-numbered page links than the lowest currently displayed.
 [X] An ellipse is displayed after the last numbered page link and before the single right arrow link if there are higher-numbered page links than the highest currently displayed.
 [X] The single right arrow link displays the next page.
 [X] The double right arrow link displays the last page.
 [] Pagination is reactive to filtered data.
 [X] Total number of page links should equal the total number of rows divided by the number of rows displayed per page.
 [] No ellipse should display if there are fewer than or the same number of pages as the number of page links displayed.
 [X] The single and double left arrow links should have no effect if the first page is currently displayed.
 [X] The single and double right arrow links should have no effect if the last page is currently displayed.
